teste

diff --git a/.github/workflows/premain-project-deployment.yml b/.github/workflows/premain-project-deployment.yml
--- a/.github/workflows/premain-project-deployment.yml
+++ b/.github/workflows/premain-project-deployment.yml
@@ -11,114 +11,114 @@ on:
       - 'API/PHP/slim/**'
       - '.github/**'
 jobs:
-  # Deploy-Preview-To-Vercel:
-  #   runs-on: ubuntu-latest
-  #   environment: pre-main
-  #   outputs:
-  #     vercel-link: ${{ steps.vercel-deploy.outputs.link }}
-  #   steps:
-  #     - uses: actions/checkout@v3
+  Deploy-Preview-To-Vercel:
+    runs-on: ubuntu-latest
+    environment: pre-main
+    outputs:
+      vercel-link: ${{ steps.vercel-deploy.outputs.link }}
+    steps:
+      - uses: actions/checkout@v3
 
-  #     - name: Install Vercel CLI
-  #       run: npm install --global vercel@latest
+      - name: Install Vercel CLI
+        run: npm install --global vercel@latest
 
-  #     - name: Install dependencies
-  #       uses: php-actions/composer@v6
-  #       with:
-  #         working_dir: "API/PHP/slim/api"
+      - name: Install dependencies
+        uses: php-actions/composer@v6
+        with:
+          working_dir: "API/PHP/slim/api"
 
-  #     - name: Create .env arquive
-  #       run: |
-  #         echo "SGBD=${{ secrets.SGBD }}" >> ./API/PHP/slim/api/.env
-  #         echo "HOST=${{ secrets.HOST }}" >> ./API/PHP/slim/api/.env
-  #         echo "PORT=${{ secrets.PORT }}" >> ./API/PHP/slim/api/.env
-  #         echo "DATABASE=${{ secrets.DATABASE }}" >> ./API/PHP/slim/api/.env
-  #         echo "USER=${{ secrets.USER }}" >> ./API/PHP/slim/api/.env
-  #         echo "PASSWD=${{ secrets.PASSWD }}" >> ./API/PHP/slim/api/.env
-  #         echo "DISPLAY_ERROR=${{ secrets.DISPLAY_ERROR }}" >> ./API/PHP/slim/api/.env
+      - name: Create .env arquive
+        run: |
+          echo "SGBD=${{ secrets.SGBD }}" >> ./API/PHP/slim/api/.env
+          echo "HOST=${{ secrets.HOST }}" >> ./API/PHP/slim/api/.env
+          echo "PORT=${{ secrets.PORT }}" >> ./API/PHP/slim/api/.env
+          echo "DATABASE=${{ secrets.DATABASE }}" >> ./API/PHP/slim/api/.env
+          echo "USER=${{ secrets.USER }}" >> ./API/PHP/slim/api/.env
+          echo "PASSWD=${{ secrets.PASSWD }}" >> ./API/PHP/slim/api/.env
+          echo "DISPLAY_ERROR=${{ secrets.DISPLAY_ERROR }}" >> ./API/PHP/slim/api/.env
 
-  #     - name: Pull Vercel Environment Information
-  #       working-directory: ./API/PHP/slim
-  #       run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
+      - name: Pull Vercel Environment Information
+        working-directory: ./API/PHP/slim
+        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
 
-  #     - name: Build Project Artifacts
-  #       working-directory: ./API/PHP/slim
-  #       run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
+      - name: Build Project Artifacts
+        working-directory: ./API/PHP/slim
+        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
 
-  #     - name: Deploy Project Artifacts to Vercel
-  #       working-directory: ./API/PHP/slim
-  #       id: vercel-deploy
-  #       run: |
-  #         vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} > deployment-url.txt
-  #         code=$?
-  #         if [ $code -eq 0 ]; then
-  #             deploymentUrl=`cat deployment-url.txt`
-  #         else
-  #             errorMessage=`cat error.txt`
-  #             echo "There was an error: $errorMessage"
-  #         fi
-  #         echo "link=$deploymentUrl" >> "$GITHUB_OUTPUT"
+      - name: Deploy Project Artifacts to Vercel
+        working-directory: ./API/PHP/slim
+        id: vercel-deploy
+        run: |
+          vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} > deployment-url.txt
+          code=$?
+          if [ $code -eq 0 ]; then
+              deploymentUrl=`cat deployment-url.txt`
+          else
+              errorMessage=`cat error.txt`
+              echo "There was an error: $errorMessage"
+          fi
+          echo "link=$deploymentUrl" >> "$GITHUB_OUTPUT"
   
-  # Mobile-Update:
-  #   runs-on: ubuntu-latest
-  #   environment: pre-main
-  #   needs: Deploy-Preview-To-Vercel
-  #   outputs:
-  #     androidId: ${{ steps.preview.outputs.androidId }}
-  #     iosId: ${{ steps.preview.outputs.iosId }}
-  #     qr: ${{ steps.preview.outputs.qr }}
-  #   steps:
-  #     - name: 🏗 Setup repo
-  #       uses: actions/checkout@v3
+  Mobile-Update:
+    runs-on: ubuntu-latest
+    environment: pre-main
+    needs: Deploy-Preview-To-Vercel
+    outputs:
+      androidId: ${{ steps.preview.outputs.androidId }}
+      iosId: ${{ steps.preview.outputs.iosId }}
+      qr: ${{ steps.preview.outputs.qr }}
+    steps:
+      - name: 🏗 Setup repo
+        uses: actions/checkout@v3
 
-  #     - name: 🏗 Setup Node
-  #       uses: actions/setup-node@v3
-  #       with:
-  #         node-version: 20.x
-  #         cache: npm
-  #         cache-dependency-path: Mobile/package-lock.json
+      - name: 🏗 Setup Node
+        uses: actions/setup-node@v3
+        with:
+          node-version: 20.x
+          cache: npm
+          cache-dependency-path: Mobile/package-lock.json
         
-  #     - name: 🏗 Setup Expo and EAS
-  #       uses: expo/expo-github-action@v8
-  #       with:
-  #         expo-version: latest
-  #         eas-version: latest
-  #         token: ${{ secrets.EXPO_TOKEN_DEV }}
+      - name: 🏗 Setup Expo and EAS
+        uses: expo/expo-github-action@v8
+        with:
+          expo-version: latest
+          eas-version: latest
+          token: ${{ secrets.EXPO_TOKEN_DEV }}
 
-  #     - name: 📦 Install dependencies
-  #       working-directory: ./Mobile
-  #       run: npm install
+      - name: 📦 Install dependencies
+        working-directory: ./Mobile
+        run: npm install
 
-  #     - name: 🚀 Create preview
-  #       uses: expo/expo-github-action/preview@v8
-  #       env:
-  #         SERVER_LINK: ${{needs.Deploy-Preview-To-Vercel.outputs.vercel-link}}
-  #         GOOGLE_MAP_API_KEY: ${{ secrets.GOOGLE_MAP_API_KEY }}
-  #       id: preview
-  #       with:
-  #         command: eas update --auto
-  #         comment: false
-  #         working-directory: ./Mobile
+      - name: 🚀 Create preview
+        uses: expo/expo-github-action/preview@v8
+        env:
+          SERVER_LINK: ${{needs.Deploy-Preview-To-Vercel.outputs.vercel-link}}
+          GOOGLE_MAP_API_KEY: ${{ secrets.GOOGLE_MAP_API_KEY }}
+        id: preview
+        with:
+          command: eas update --auto
+          comment: false
+          working-directory: ./Mobile
 
-  #     - name: teste1
-  #       run: |
-  #         echo "Id ${{ steps.preview.outputs.groupId }}"
-  #         echo "QRCode: ${{ steps.preview.outputs.qr }}"
+      - name: teste1
+        run: |
+          echo "Id ${{ steps.preview.outputs.groupId }}"
+          echo "QRCode: ${{ steps.preview.outputs.qr }}"
 
-  #         echo "androidId ${{ steps.preview.outputs.androidId }}"
-  #         echo "androidQR ${{ steps.preview.outputs.androidQR }}"
+          echo "androidId ${{ steps.preview.outputs.androidId }}"
+          echo "androidQR ${{ steps.preview.outputs.androidQR }}"
 
-  #         echo "iosId ${{ steps.preview.outputs.iosId }}"
-  #         echo "iosQR ${{ steps.preview.outputs.iosQR }}"
+          echo "iosId ${{ steps.preview.outputs.iosId }}"
+          echo "iosQR ${{ steps.preview.outputs.iosQR }}"
 
-  #         echo "androidId=${{ steps.preview.outputs.androidId }}" >> "$GITHUB_OUTPUT"
-  #         echo "iosId=${{ steps.preview.outputs.iosId }}" >> "$GITHUB_OUTPUT"
-  #         echo "androidQR=${{ steps.preview.outputs.qr }}" >> "$GITHUB_OUTPUT"
+          echo "androidId=${{ steps.preview.outputs.androidId }}" >> "$GITHUB_OUTPUT"
+          echo "iosId=${{ steps.preview.outputs.iosId }}" >> "$GITHUB_OUTPUT"
+          echo "androidQR=${{ steps.preview.outputs.qr }}" >> "$GITHUB_OUTPUT"
   
   Update-Readme:
     runs-on: ubuntu-latest
     environment: pre-main
-    # needs: Mobile-Update
+    needs: Mobile-Update
     steps:
       - name: 🏗 Setup repo
         uses: actions/checkout@v3
@@ -128,13 +128,13 @@ jobs:
 
       - name: teste2
         run: |
-          # androidId=${{ needs.Mobile-Update.outputs.androidId }}
-          # iosId=${{ needs.Mobile-Update.outputs.iosId }}
-          # qrCode=${{ needs.Mobile-Update.outputs.qr }}
-          qrCode="https://qr.expo.dev/eas-update?projectId=123"
+          androidId=${{ needs.Mobile-Update.outputs.androidId }}
+          iosId=${{ needs.Mobile-Update.outputs.iosId }}
+          qrCode=${{ needs.Mobile-Update.outputs.qr }}
+          # qrCode="https://qr.expo.dev/eas-update?projectId=123"
 
-          # sed -i "/^PetCare Android:/,/exp:\/\/u.expo.dev\/update\/.*/s#exp://u.expo.dev/update/.*#exp://u.expo.dev/update/$androidId#" README.md
-          # sed -i "/^PetCare iPhone:/,/exp:\/\/u.expo.dev\/update\/.*/s#exp://u.expo.dev/update/.*#exp://u.expo.dev/update/$iosId#" README.md
+          sed -i "/^PetCare Android:/,/exp:\/\/u.expo.dev\/update\/.*/s#exp://u.expo.dev/update/.*#exp://u.expo.dev/update/$androidId#" README.md
+          sed -i "/^PetCare iPhone:/,/exp:\/\/u.expo.dev\/update\/.*/s#exp://u.expo.dev/update/.*#exp://u.expo.dev/update/$iosId#" README.md
           sed -i "s#https://qr.expo.dev/eas-update?projectId=[^ )\x22]*#$qrCode#g" README.md
 
           git config user.name LuizMateuss
